### ISSUE TITLE
Getting error while building the gradle project. No support for ReadyAPI Version 2.7.0

### ISSUE THREAD

**Issue by Aksh165** [reportportal/agent-java-soapui#10]
Follow the same setup provided in the ReadMe section of the gradle project, but getting issue while project is build. Also this version of the project is not supporting 2.7.0 version of ReadyAPI. Please help

**Comment by f4br3** [comment]
@Aksh165 Could you leave more information about your build issue? Because as i could see everything works fine.
![Untitled11](https://user-images.githubusercontent.com/6077514/61368694-1bb6be80-a897-11e9-9f7a-2fcc45f9f9a5.png)

**Comment by f4br3** [comment]
@Aksh165 About ReadyAPI support, I'm currently using this agent with 2.7.0 version and it correctly sends logs to the ReportPortal. But every time you need to set test suite to run from your ReadyAPI project, somehow it not works when you want to run whole ReadyAPI project with all test suites at a time, i think it's a bug. 

@DzmitryHumianiuk Could somebody take a look on it?

**Comment by DzmitryHumianiuk** [comment]
@f4br3 it also can be a limitation of Free version against PRO version

**Comment by staind825** [comment]
I've also tried pulling the project into Eclipse and cannot build. Not sure whats going on:
![buildissue](https://user-images.githubusercontent.com/36093419/61389939-d2ab3e00-a887-11e9-95e5-2f42388a0395.png)

**Comment by f4br3** [comment]
@DzmitryHumianiuk Completely sure, this is agent problem, because i'm using SoapUI Pro version in ReadyAPI and i don't have any limitations in it.

**Comment by DzmitryHumianiuk** [comment]
@f4br3 ok. Will take a look next week

**Comment by DzmitryHumianiuk** [comment]
@staind825 is it a Gradle related issue?

**Comment by f4br3** [comment]
@staind825 Something wrong with you Gradle here, i think it happens not only in current project.

**Comment by Aksh165** [comment]
@f4br3 Hey, If this work for you. would you mind helping me with the .zip file. I will extract the all the jar files and place them to the **SOAPUI_HOME/bin/ext** and **SOAPUI_HOME/bin/listeners.**

**Comment by Aksh165** [comment]
> @Aksh165 Could you leave more information about your build issue? Because as i could see everything works fine.
> ![Untitled11](https://user-images.githubusercontent.com/6077514/61368694-1bb6be80-a897-11e9-9f7a-2fcc45f9f9a5.png)

![Capture](https://user-images.githubusercontent.com/17594396/61431469-3480ac00-a94b-11e9-8220-9e548fc86f7e.PNG)

This is the issue I am getting while building the gradle project from my laptop.

**Comment by f4br3** [comment]
@Aksh165 No problem, here is the .zip that you need - [soapui-4.0.0-SNAPSHOT-full.zip](https://github.com/reportportal/agent-java-soapui/files/3405635/soapui-4.0.0-SNAPSHOT-full.zip)

**Comment by f4br3** [comment]
> ![Capture](https://user-images.githubusercontent.com/17594396/61431469-3480ac00-a94b-11e9-8220-9e548fc86f7e.PNG)
> 
> This is the issue I am getting while building the gradle project from my laptop.

This issue related to your network, because Gradle trying to get all of the imports needed to build a project, but it cannot be resolved via DNS.

**Comment by Aksh165** [comment]
> > ![Capture](https://user-images.githubusercontent.com/17594396/61431469-3480ac00-a94b-11e9-8220-9e548fc86f7e.PNG)
> > This is the issue I am getting while building the gradle project from my laptop.
> 
> This issue related to your network, because Gradle trying to get all of the imports needed to build a project, but it cannot be resolved via DNS.

Yup that may be the scenario. I will work with the team here in my office. Also thanks for the .zip file, i can work with this as of now.

**Comment by Aksh165** [comment]
> @Aksh165 No problem, here is the .zip that you need - [soapui-4.0.0-SNAPSHOT-full.zip](https://github.com/reportportal/agent-java-soapui/files/3405635/soapui-4.0.0-SNAPSHOT-full.zip)

Will this work with ReadyAPI 2.7.0 version also ?

**Comment by f4br3** [comment]
> Will this work with ReadyAPI 2.7.0 version also ?
>> But every time you need to set test suite to run from your ReadyAPI project, somehow it not works when you want to run whole ReadyAPI project with all test suites at a time, i think it's a bug.

Correct, but because of the bug **(i hope it will be fixed soon)** only as how i describe it above. You just need to run your tests by **separate test suites**, not like whole project run.

**Comment by f4br3** [comment]
> @f4br3 ok. Will take a look next week

@DzmitryHumianiuk Do you already have any information about this issue?

**Comment by DzmitryHumianiuk** [comment]
@f4br3 still in next sprint.
team postponed this, since we have code freeze for v5

**Comment by jainriteshkumar17** [comment]
I tried on the Test suite level but it is still not working for readyapi 2.7.0 can anyone help

**Comment by jainriteshkumar17** [comment]
i have tried adding the properties from report portal in the custom properties of individual test suite in ready API but didn't work.
are we sure about same zip being used for soap UI and ready API or there could be some difference as Soap UI is free ware and Ready API is a licensed one.

**Comment by f4br3** [comment]
> i have tried adding the properties from report portal in the custom properties of individual test suite in ready API but didn't work.

You need to add these properties as 'Custom Properties' for the project, not like properties of individual test suite.

> are we sure about same zip being used for soap UI and ready API or there could be some difference as Soap UI is free ware and Ready API is a licensed one.

I'm sure that there is no difference for this .jar between SoapUI and ReadyAPI.

**Comment by f4br3** [comment]
> @f4br3 still in next sprint.
> team postponed this, since we have code freeze for v5

@DzmitryHumianiuk 
Any approximate time when this sprint will happens and bug will be fixed?

**Comment by lio972** [comment]
Hi i have issue with soapui. Nothing is sent to  rp; When i modify  soapui logging file to add appender etc... i even get exception

```
Wed Aug 14 14:30:59 CEST 2019:INFO:log4j:ERROR Could not create an Appender. Reported error follows.
java.lang.ClassNotFoundException: com.epam.ta.reportportal.soapui.log.SoapUILogAppender
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Unknown Source)
	at org.apache.log4j.helpers.Loader.loadClass(Loader.java:178)
	at org.apache.log4j.xml.DOMConfigurator.parseAppender(DOMConfigurator.java:174)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:150)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:604)
	at org.apache.log4j.xml.XMLWatchdog.doOnChange(DOMConfigurator.java:861)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:88)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:57)
	at org.apache.log4j.xml.XMLWatchdog.<init>(DOMConfigurator.java:853)
	at org.apache.log4j.xml.DOMConfigurator.configureAndWatch(DOMConfigurator.java:584)
	at com.eviware.soapui.DefaultSoapUICore.initLog(DefaultSoapUICore.java:492)
	at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:136)
	at com.eviware.soapui.DefaultSoapUICore.<init>(DefaultSoapUICore.java:132)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.createSoapUICore(AbstractSoapUIRunner.java:216)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:192)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:137)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.runFromCommandLine(AbstractSoapUIRunner.java:112)
	at com.eviware.soapui.tools.SoapUITestCaseRunner.main(SoapUITestCaseRunner.java:122)
log4j:ERROR Could not parse file [D:\sources\Program Files\SmartBear\SoapUI-5.5.0\SoapUI-5.5.0\bin\soapui-log4j.xml].
java.lang.NullPointerException
	at java.util.Hashtable.put(Unknown Source)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByName(DOMConfigurator.java:151)
	at org.apache.log4j.xml.DOMConfigurator.findAppenderByReference(DOMConfigurator.java:163)
	at org.apache.log4j.xml.DOMConfigurator.parseChildrenOfLoggerElement(DOMConfigurator.java:425)
	at org.apache.log4j.xml.DOMConfigurator.parseCategory(DOMConfigurator.java:345)
	at org.apache.log4j.xml.DOMConfigurator.parse(DOMConfigurator.java:827)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:712)
	at org.apache.log4j.xml.DOMConfigurator.doConfigure(DOMConfigurator.java:604)
	at org.apache.log4j.xml.XMLWatchdog.doOnChange(DOMConfigurator.java:861)
	at org.apache.log4j.helpers.FileWatchdog.checkAndConfigure(FileWatchdog.java:88)
	at org.apache.log4j.helpers.FileWatchdog.<init>(FileWatchdog.java:57)
	at org.apache.log4j.xml.XMLWatchdog.<init>(DOMConfigurator.java:853)
	at org.apache.log4j.xml.DOMConfigurator.configureAndWatch(DOMConfigurator.java:584)
	at com.eviware.soapui.DefaultSoapUICore.initLog(DefaultSoapUICore.java:492)
	at com.eviware.soapui.DefaultSoapUICore.init(DefaultSoapUICore.java:136)
	at com.eviware.soapui.DefaultSoapUICore.<init>(DefaultSoapUICore.java:132)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.createSoapUICore(AbstractSoapUIRunner.java:216)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:192)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.run(AbstractSoapUIRunner.java:137)
	at com.eviware.soapui.tools.AbstractSoapUIRunner.runFromCommandLine(AbstractSoapUIRunner.java:112)
	at com.eviware.soapui.tools.SoapUITestCaseRunner.main(SoapUITestCaseRunner.java:122)

```

**Comment by lio972** [comment]
I've build the project with gradle, done the install in soapui 5.5 folder en configure my project with the parameter

![image](https://user-images.githubusercontent.com/1936347/63030230-46099500-beb2-11e9-8ea5-2251394cb19f.png)


i've connected to RP as an admin and created a project  named soapui. But not activity  can be detected in RP

![image](https://user-images.githubusercontent.com/1936347/63030422-8f59e480-beb2-11e9-81c5-d6964dd98e72.png)

**Comment by f4br3** [comment]
> Hi i have issue with soapui. Nothing is sent to rp; When i modify soapui logging file to add appender etc... i even get exception

Hmmm, i don't think, that you need to modify something in `soapui-log4j.xml` file, just revert this file back to default, add `soapui-4.0.0-SNAPSHOT-all.jar` to ext folder and `reportportal-listeners.xml` to listeners folder, restart SoapUI, then try to run it again.

**Comment by jainriteshkumar17** [comment]
is there some different provisions for report portal hosted on https protocol.

because i am not able to see the report in RP whil same thing when i am doing with http i am able to get the same but that is on a different server. https is not woking.

Can someone throw some light on this.

**Comment by Dexter-Clone** [comment]
Hello @f4br3  & @DzmitryHumianiuk DzmitryHumianiuk, We are looking if there are some other configuration needs to be done if report portal is hosted on https secure network. 

As of now, we have setup everything on report portal sandbox sever and our ReadyAPI (TestSuite report) and SOAPUI (project report) are getting added to the portal. But when I have moved the setup to Production which is a secured network (https), we are facing issue.

Would really appreciate your help on this.

**Comment by Dexter-Clone** [comment]
@DzmitryHumianiuk It just that execution from SOAPUI is finished but the reports are not published on ReportPort.

I will let you know if I face any issues once I will add the certificates for ReadyAPI & SOAPUI and add those to project properties.

**Comment by Dexter-Clone** [comment]
@DzmitryHumianiuk Got this thing working after I have installed certificate for ReadyAPI. Thank you.

Requesting you to please let us know when the fix would role out which @f4br3 reported in this conversation,
https://github.com/reportportal/agent-java-soapui/issues/10#issuecomment-516325285

**Comment by lio972** [comment]
hi @f4br3 i've spent 3 day  on reportportal, looking  for a production plateform for my client. I finally give up. Too complicated, so few information. I'll stick to ELK and Allure.io. I done what you proposed by doesn't work. Neither jenkins or soapui send valuable data.

Your project ReportPortal look great. I think that i'll have a look in a few years.

Take care.

**Comment by jaysidd** [comment]
> @DzmitryHumianiuk It just that execution from SOAPUI is finished but the reports are not published on ReportPort.
> 
> I will let you know if I face any issues once I will add the certificates for ReadyAPI & SOAPUI and add those to project properties.



> @DzmitryHumianiuk Got this thing working after I have installed certificate for ReadyAPI. Thank you.
> 
> Requesting you to please let us know when the fix would role out which @f4br3 reported in this conversation, [#10 (comment)](https://github.com/reportportal/agent-java-soapui/issues/10#issuecomment-516325285)

Hi, can you please provide steps on adding the certificate in SOAPUI for report portal.
