### ISSUE TITLE
Integration with ReadyAPI no longer works beginning with ReadyAPI 3.52.0

### ISSUE THREAD

**Issue by pjdjr** [reportportal/agent-java-soapui#23]
Is Report Portal still supporting the integration with ReadyAPI? The integration seems to have broken with version 3.52.0 of ReadyAPI. As of 3.52.0, ReadyAPI no longer supports "AMF Request test steps," which seem to be needed by Report Portal. My test suite does not use this request test step type, but the error in the logs seems to indicate Report Portal does.

`13:39:18,685 ERROR [AbstractTestCaseRunner] An error occurred when notifying the listener before the test step execution.
.
.
.
Caused by: java.lang.NoClassDefFoundError: com/eviware/soapui/impl/wsdl/teststeps/AMFRequestTestStep
	at com.epam.reportportal.soapui.parameters.TestStepType.<clinit>(TestStepType.java:36) ~[?:?]
	at com.epam.reportportal.soapui.service.StepBasedSoapUIServiceImpl.startTestStep(StepBasedSoapUIServiceImpl.java:187) ~[?:?]
	at com.epam.reportportal.soapui.listeners.RPTestRunListener.beforeStep(RPTestRunListener.java:54) ~[?:?]
.
.
.
Caused by: java.lang.ClassNotFoundException: com.eviware.soapui.impl.wsdl.teststeps.AMFRequestTestStep
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at com.eviware.soapui.plugins.JarClassLoader.loadClass(JarClassLoader.java:71) ~[ready-api-soapui-pro-3.52.0.jar:3.52.0]
	at com.epam.reportportal.soapui.parameters.TestStepType.<clinit>(TestStepType.java:36) ~[?:?]
	at com.epam.reportportal.soapui.service.StepBasedSoapUIServiceImpl.startTestStep(StepBasedSoapUIServiceImpl.java:187) ~[?:?]
	at com.epam.reportportal.soapui.listeners.RPTestRunListener.beforeStep(RPTestRunListener.java:54) ~[?:?]
`

**Comment by pjdjr** [comment]
Is anyone from Report Portal able to comment on this issue? Is there a workaround for this problem, or is it something you might fix? Thank you.
