### ISSUE TITLE
SoapUI 4.3.0 integration error

### ISSUE THREAD

**Issue by learnappium** [reportportal/agent-java-soapui#4]
Hi,
Hi , I am using reportportal soapUI listner for integrationg of test automation to reportportal server.
we were using soapUI : 2.0.0 and it was working fine (we were getting test result on report portal ) server.

Recently we have updated SoapUI (ReadyAPI ) version 2.3.0.
updated soapUI log4j xml file
Added report portal appended and logger.
Installed readyAPI plugin and added soapui reportportal jar file on lib and listener folder.
Now when we running out test , we are getting following error
````
Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 
Error Type: INCORRECT_REQUEST
Stack Trace: 
com.epam.reportportal.exception.ReportPortalClientException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 
Error Type: INCORRECT_REQUEST
Stack Trace: 
	at com.epam.reportportal.service.ReportPortalErrorHandler.handleClientError(ReportPortalErrorHandler.java:47)
	at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:73)
	at com.epam.reportportal.restclient.endpoint.DefaultErrorHandler.handle(DefaultErrorHandler.java:40)
	at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.executeInternal(HttpClientRestEndpoint.java:341)
	at com.epam.reportportal.restclient.endpoint.HttpClientRestEndpoint.post(HttpClientRestEndpoint.java:106)
	at com.epam.reportportal.service.ReportPortalService.startTestItem(ReportPortalService.java:246)
	at com.epam.reportportal.soapui.service.SoapUIServiceImpl.startTestCase(SoapUIServiceImpl.java:184)
	at com.epam.reportportal.soapui.listeners.RPTestSuiteRunListener.beforeTestCase(RPTestSuiteRunListener.java:77)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.eviware.soapui.plugins.PluginProxies$DelegatingHandler.invoke(PluginProxies.java:116)
	at com.sun.proxy.$Proxy48.beforeTestCase(Unknown Source)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner$4.notifyListener(WsdlTestSuiteRunner.java:258)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.notifyListeners(WsdlTestSuiteRunner.java:286)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.notifyBeforeRunTestCase(WsdlTestSuiteRunner.java:255)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.runSequential(WsdlTestSuiteRunner.java:171)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.internalRun(WsdlTestSuiteRunner.java:119)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestSuiteRunner.internalRun(WsdlTestSuiteRunner.java:1)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Error during starting step:
Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' shouldn't be null.] 
Error Type: INCORRECT_REQUEST
Stack Trace: 
Error during finishing step:
No enum constant com.epam.reportportal.soapui.parameters.TestStatus.PASS
java.lang.IllegalArgumentException: No enum constant com.epam.reportportal.soapui.parameters.TestStatus.PASS
	at java.lang.Enum.valueOf(Unknown Source)
	at com.epam.reportportal.soapui.parameters.TestStatus.valueOf(TestStatus.java:1)
	at com.epam.reportportal.soapui.parameters.TestStatus.fromSoapUIStep(TestStatus.java:44)
	at com.epam.reportportal.soapui.service.SoapUIServiceImpl.finishTestStep(SoapUIServiceImpl.java:264)
	at com.epam.reportportal.soapui.listeners.RPTestRunListener.afterStep(RPTestRunListener.java:68)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.eviware.soapui.plugins.PluginProxies$DelegatingHandler.invoke(PluginProxies.java:116)
	at com.sun.proxy.$Proxy47.afterStep(Unknown Source)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.notifyListenersAfterStep(AbstractTestCaseRunner.java:297)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.runTestStep(AbstractTestCaseRunner.java:271)
	at com.eviware.soapui.impl.wsdl.testcase.WsdlTestCaseRunner.runCurrentTestStep(WsdlTestCaseRunner.java:50)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:170)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestCaseRunner.internalRun(AbstractTestCaseRunner.java:1)
	at com.eviware.soapui.impl.wsdl.support.AbstractTestRunner.run(AbstractTestRunner.java:129)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by avarabyeu** [comment]
hi @learnappium 
Add required properties to your soapUI project (as custom properties):
```
rp.endpoint=https://rp.epam.com
rp.uuid={YOUR_TOKEN}
rp.project={YOUR_PROJECT}
rp.launch={NAME_OF_YOUR_LAUNCH}
```
- Reload your project

**Comment by learnappium** [comment]
@avarabyeu  yes,  thats configuration already in place in each test project.
but still getting same issue

**Comment by avarabyeu** [comment]
@learnappium could you please share with us some simple demo project so we can reproduce the issue

**Comment by learnappium** [comment]
@avarabyeu  attached demo-soapUI project xml file and soapUI log4j file


[soapUI_Project_and_Log4j.zip](https://github.com/reportportal/agent-java-soapui/files/1832203/soapUI_Project_and_Log4j.zip)

same kind of issue i am getting with readyAPI rp plugin

**Comment by avarabyeu** [comment]
@learnappium I've update agent-java-soapui project. Could you please check if it fixes the issue and let me know? 
Thank you in advance!

**Comment by learnappium** [comment]
@avarabyeu   Thanks for quick response.
I have built new jar file with latest code change.
but unfortunately still result not getting posted.
Project ran without logging any failure message on Readyapi/SoapUI log
